name: PartAssembly
channels:
  - pytorch
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - cffi=1.13.2=py37h2e261b9_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - freetype=2.9.1=h8a8886c_1
  - h5py=2.10.0=py37h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - intel-openmp=2019.4=243
  - jpeg=9b=h024ee3a_2
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py_0
  - openssl=1.1.1d=h7b6447c_3
  - pillow=7.0.0=py37hb39fc2d_0
  - pip=19.3.1=py37_0
  - progressbar=2.5=py_0
  - pycparser=2.19=py_0
  - python=3.7.6=h0371630_2
  - pytorch=1.1.0=cuda100py37he554f03_0
  - readline=7.0=h7b6447c_5
  - setuptools=44.0.0=py37_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.2.2=py_3
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.9.0
    - backcall==0.1.0
    - blender==1.4
    - cachetools==4.0.0
    - chamfer-ext==0.0.0
    - chardet==3.0.4
    - cycler==0.10.0
    - decorator==4.4.1
    - future==0.18.2
    - google-auth==1.11.0
    - google-auth-oauthlib==0.4.1
    - grpcio==1.26.0
    - idna==2.8
    - ipython==7.11.1
    - ipython-genutils==0.2.0
    - jedi==0.16.0
    - joblib==0.14.1
    - kiwisolver==1.2.0
    - markdown==3.1.1
    - matplotlib==3.2.1
    - networkx==2.4
    - numpy==1.18.1
    - oauthlib==3.1.0
    - parso==0.6.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - plyfile==0.7.1
    - prompt-toolkit==3.0.3
    - protobuf==3.11.2
    - ptyprocess==0.6.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyglet==1.4.10
    - pygments==2.5.2
    - pyparsing==2.4.6
    - pyquaternion==0.9.5
    - python-dateutil==2.8.1
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - sklearn==0.0
    - tensorboard==2.0.2
    - tensorboardx==2.0
    - torch==1.4.0
    - torch-scatter==2.0.4
    - tqdm==4.42.0
    - traitlets==4.3.3
    - trimesh==3.5.16
    - urllib3==1.25.8
    - wcwidth==0.1.8
    - werkzeug==0.16.1
prefix: /home/root/anaconda3/envs/PartAssembly

